apiVersion: v1
kind: Service
metadata:
  name: next-node-webapp
  labels:
    run: next-node-webapp
spec:
  ports:
  - port: 3000
    protocol: TCP
  selector:
    app: next-node-webapp
  type: ClusterIP